# taken from https://rimdev.io/building-net-core-on-travis-ci/
language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-1-003177
before_script:
 - chmod a+x ./build.sh
script:
 - ./build.sh