# taken from https://rimdev.io/building-net-core-on-travis-ci/
language: csharp
dist: trusty
sudo: required
mono: none
dotnet: dotnet-dev-1.0.4
before_script:
 - chmod a+x ./build.sh
script:
 - ./build.sh